### ISSUE TITLE
Undefined reference to `mpr121_autoconfig'

### ISSUE THREAD

**Issue by TuriSc** [antgon/pico-mpr121#1]
Seems like mpr121_autoconfig is invoked but not defined anywhere in the library.

Building the examples is only possible after commenting out this line:
`mpr121_autoconfig(&mpr121);`

**Comment by anand-010** [comment]
I have the same problem have you solved it?.

**Comment by anand-010** [comment]
it's in the mpr121_init no need to call mpr121_autoconfig.
